### ISSUE TITLE
How to remove "You are using stable version of plugin" message on join?

### ISSUE THREAD

**Issue by PJGamerr** [EncryptSL/CENSOR-RELOADED-ISSUES#21]
How to remove "You are using stable version of plugin" message on join?

**Comment by EncryptSL** [comment]
I released new version 4.3.0 - Where was this message deleted, only if new version was released plugin sends message about new version.

https://www.spigotmc.org/resources/censor-reloaded-advanced-chat-filter.14752/update?update=439345

**Comment by T4B999** [comment]
I don't have any of these issues but with the new version getting this error 

```
[03:00:03 ERROR]: Could not pass event AsyncPlayerChatEvent to CensorReloaded v4.3.0
java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.file.FileConfiguration.getString(String)" because the return value of "encryptsl.cekuj.net.bukkit.config.Configurator.getLang()" is null
        at encryptsl.cekuj.net.bukkit.module.WebAddress.executeControl(WebAddress.java:24) ~[CensorReloadedBukkit-4.3.0.jar:?]
        at encryptsl.cekuj.net.bukkit.listeners.AsyncChat.asyncChat(AsyncChat.java:30) ~[CensorReloadedBukkit-4.3.0.jar:?]
        at encryptsl.cekuj.net.bukkit.listeners.AsyncChat.execute(AsyncChat.java:24) ~[CensorReloadedBukkit-4.3.0.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:230) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:115) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:64) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2261) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2172) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2138) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket$1.run(ServerboundChatPacket.java:40) ~[app:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by EncryptSL** [comment]
@T4B999 You can send your config.yml and your current using lang file.

**Comment by EncryptSL** [comment]
@T4B999 You can try recreate config.yml

Stop your server, delete config.yml and if you have old lang files you can remove lang folder.

**Comment by T4B999** [comment]
> You are using stable version of plugin

'You are using stable version of plugin' this message only get op players right?

**Comment by EncryptSL** [comment]
in version 4.3.0 - This message "You are using stable version of plugin" was removed. Only if new version was uploaded plugin show notification about new version. This message still used only in console.

Yes op players or players with permission **censor.update** can see message about new version.
