### ISSUE TITLE
New censor version dont work..

### ISSUE THREAD

**Issue by PJGamerr** [EncryptSL/CENSOR-RELOADED-ISSUES#22]
[12:03:22] [main/WARN]: Exception encountered when loading plugin: CensorReloaded
java.lang.NullPointerException: null
	at net.md_5.bungee.config.YamlConfiguration.save(YamlConfiguration.java:65) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at net.md_5.bungee.config.YamlConfiguration.save(YamlConfiguration.java:58) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at encryptsl.cekuj.net.bungee.config.Configurator.saveLangConfig(Configurator.java:111) ~[?:?]
	at encryptsl.cekuj.net.bungee.config.Configurator.SetLang(Configurator.java:55) ~[?:?]
	at encryptsl.cekuj.net.bungee.config.Configurator.loadLang(Configurator.java:139) ~[?:?]
	at encryptsl.cekuj.net.bungee.CensorReloadedBungee.onEnable(CensorReloadedBungee.java:36) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:356) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:320) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:54) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]

**Comment by EncryptSL** [comment]
Fixed in https://github.com/EncryptSL/CENSOR-RELOADED-ISSUES/releases/tag/4.3.1
