### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by PJGamerr** [EncryptSL/CENSOR-RELOADED-ISSUES#23]
The plugin work perfectly but console send this:

[21:05:09] [Netty Worker IO Thread #11/WARN]: Error dispatching event ChatEvent(super=TargetedEvent(sender=LaMari2001, receiver=net.md_5.bungee.ServerConnection@3682f8f1), cancelled=false, message=porco ****) to listener encryptsl.cekuj.net.bungee.listeners.AsyncChat@570a62a5
java.lang.NoClassDefFoundError: org/bukkit/Bukkit
	at encryptsl.cekuj.net.core.SharedCore.bukkitColors(SharedCore.java:55) ~[?:?]
	at encryptsl.cekuj.net.core.api.ComponentFactory.chatFormat(ComponentFactory.java:18) ~[?:?]
	at encryptsl.cekuj.net.bungee.CensorReloadedBungee.sendToAdmin(CensorReloadedBungee.java:110) ~[?:?]
	at encryptsl.cekuj.net.bungee.module.AntiSwear.executeControl(AntiSwear.java:28) ~[?:?]
	at encryptsl.cekuj.net.bungee.listeners.AsyncChat.asyncChat(AsyncChat.java:25) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:48) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:510) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:170) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:78) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:132) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at com.lahuca.botsentry.bungee.m.channelRead(Unknown Source) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.ClassNotFoundException: org.bukkit.Bukkit
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.18-R0.1-SNAPSHOT:6854179:unknown]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
	... 57 more

**Comment by EncryptSL** [comment]
Fixed in [4.3.3](https://github.com/EncryptSL/CENSOR-RELOADED-ISSUES/releases/tag/4.3.3)

**Comment by PJGamerr** [comment]
thank you very much, now the plugin works perfectly, but when I enter it tells me to update it D:

**Comment by EncryptSL** [comment]
Sorry for trouble, enjoy.
