### ISSUE TITLE
word 

### ISSUE THREAD

**Issue by Shucai99** [EncryptSL/CENSOR-RELOADED-ISSUES#9]
**Information about the bug**
Send whats wrong
hello I see you nice plugin i have 1-2  good tips and 1 bugs you can make dat you can add /addword  then the word can the ips with hypxiel.net  like don t work 
**MineCraft Server version and Platform:**
 - Platform: [e.g. Spigot]
 - Server Version: [e.g. 1.16.1]
1.16.5
Paper
**Additional context**

**Comment by EncryptSL** [comment]
You can try change adw_rgx on this is fast fix. `\b(\w{1,9}):\/\/|(www\.)?([a-zA-Z9!@#$%^&*(),.?])+(\W|\d|_|\s)*(\d|\W(\w{2,3}))`

With command for addword, this is more advanced because, words are in regex filter.

**Comment by EncryptSL** [comment]
In next build will this regex by default.

**Comment by EncryptSL** [comment]
Implemented in to Config, 6330e56985a12b37f9bc2def709bc4f21fd3c30a

**Comment by Shucai99** [comment]
musst i add dat  to config or in the filter list?

**Comment by Shucai99** [comment]
https://pastebin.com/32aVJQMP so  it dont  work

**Comment by EncryptSL** [comment]
This is default config with fix. https://github.com/EncryptSL/CENSOR-RELOADED-ISSUES/blob/master/config.yml
In your config is problem with multiple filters, adw_rgx in config.yml must have only one regex filter.

You can copy this configuration into your on server.

**Comment by Shucai99** [comment]
yeah but  ips like .at, .de and more  and you add it or? how?

**Comment by Shucai99** [comment]
https://i.imgur.com/6iDMqaR.png don t work?

**Comment by Shucai99** [comment]
and block webspls

**Comment by EncryptSL** [comment]
This is test for websites detection, 
![image](https://user-images.githubusercontent.com/9441083/117057968-5fa1de80-ad1e-11eb-8acf-047b723ac989.png)

This is test for ips,
![image](https://user-images.githubusercontent.com/9441083/117058557-10a87900-ad1f-11eb-9d74-cc81d8ab73bb.png)

All working, if you have another plugin with detection or chat formatting there is probably conflicting.

Sorry for troubles but i don't have mutch time for solving problems, now. 

In config.yml is value for ips_rgx and adw_rgx, IPS is for Numeric detection and adw_rgx is for Website detection and DNS IP Adress like, play.hypixel.net, hypixel.at, https://hypixel.net, http://example.com.

**Comment by Shucai99** [comment]
ok  but why it don t  work  like my screen ? it dont work with  number ip  ? and wahts  the program what you use there https://i.imgur.com/FYVq8vl.png  https://i.imgur.com/OwnhoHb.png

**Comment by Shucai99** [comment]
https://pastebin.com/3Jqwg59U  Lang  on german

**Comment by EncryptSL** [comment]
Test of detection in minecraft. There is all working without problem.
![image](https://user-images.githubusercontent.com/9441083/117184774-65102f00-add9-11eb-8080-3fd054f0265b.png)
Can you please send me list of your plugins.

**Comment by Shucai99** [comment]
i test it  without  pl and it  dont wwork

**Comment by EncryptSL** [comment]
You have new version of my plugin 4.1.1 is new version ?
And in this version i don't evidenting any problem with detection.
I tested all and there is no problem.

I don't know what you have bad on your server.
Plugin working good, i changed regex detection and now works.

https://www.spigotmc.org/resources/censor-reloaded-advanced-chat-filter.14752/update?update=401560

**Comment by Shucai99** [comment]
i see it when i use ess chat it dont work  and the plugin dont load   now idkwhy u need theserver log right?

**Comment by Shucai99** [comment]
[17:17:35 WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[17:17:38 WARN]: Legacy plugin CensorReloaded v4.1.1 does not specify an api-version.
[17:17:38 ERROR]: Could not load 'plugins\CensorReloaded-4.1.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: encryptsl/cekuj/net/CensorReloaded has been compiled by a more recent version of the Java Runtime (class file version 58.0), this version of the Java Runtime only recognizes class file versions up to 55.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[patched_1.16.5.jar:git-Paper-649]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.16.5.jar:git-Paper-649]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.16.5.jar:git-Paper-649]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:389) ~[patched_1.16.5.jar:git-Paper-649]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:252) ~[patched_1.16.5.jar:git-Paper-649]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1065) ~[patched_1.16.5.jar:git-Paper-649]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-649]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.UnsupportedClassVersionError: encryptsl/cekuj/net/CensorReloaded has been compiled by a more recent version of the Java Runtime (class file version 58.0), this version of the Java Runtime only recognizes class file versions up to 55.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:178) ~[patched_1.16.5.jar:git-Paper-649]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216) ~[patched_1.16.5.jar:git-Paper-649]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:122) ~[patched_1.16.5.jar:git-Paper-649]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Paper-649]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:398) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:79) ~[patched_1.16.5.jar:git-Paper-649]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.5.jar:git-Paper-649]
        ... 7 more
[17:17:38 INFO]: Server permissions file permissions.yml is empty, ignoring it
[17:17:38 INFO]: Preparing level "world"
[17:17:38 INFO]: -------- World Settings For [world] --------
[17:17:38 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[17:17:38 INFO]: View Distance: 10
[17:17:38 INFO]: Item Merge Radius: 2.5
[17:17:38 INFO]: Item Despawn Rate: 6000
[17:17:38 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[17:17:38 INFO]: Mob Spawn Range: 6
[17:17:38 INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[17:17:38 INFO]: Nerfing mobs spawned from spawners: false
[17:17:38 INFO]: Zombie Aggressive Towards Villager: true
[17:17:38 INFO]: Cactus Growth Modifier: 100%
[17:17:38 INFO]: Cane Growth Modifier: 100%
[17:17:38 INFO]: Melon Growth Modifier: 100%
[17:17:38 INFO]: Mushroom Growth Modifier: 100%
[17:17:38 INFO]: Pumpkin Growth Modifier: 100%
[17:17:38 INFO]: Sapling Growth Modifier: 100%
[17:17:38 INFO]: Beetroot Growth Modifier: 100%
[17:17:38 INFO]: Carrot Growth Modifier: 100%
[17:17:38 INFO]: Potato Growth Modifier: 100%
[17:17:38 INFO]: Wheat Growth Modifier: 100%
[17:17:38 INFO]: NetherWart Growth Modifier: 100%
[17:17:38 INFO]: Vine Growth Modifier: 100%
[17:17:38 INFO]: Cocoa Growth Modifier: 100%
[17:17:38 INFO]: Bamboo Growth Modifier: 100%
[17:17:38 INFO]: SweetBerry Growth Modifier: 100%
[17:17:38 INFO]: Kelp Growth Modifier: 100%
[17:17:38 INFO]: Experience Merge Radius: 3.0
[17:17:38 INFO]: Max TNT Explosions: 100
[17:17:38 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[17:17:38 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[17:17:38 INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[17:17:38 INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[17:17:38 INFO]: -------- World Settings For [world_nether] --------
[17:17:38 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[17:17:38 INFO]: View Distance: 10
[17:17:38 INFO]: Item Merge Radius: 2.5
[17:17:38 INFO]: Item Despawn Rate: 6000
[17:17:38 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[17:17:38 INFO]: Mob Spawn Range: 6
[17:17:38 INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[17:17:38 INFO]: Nerfing mobs spawned from spawners: false
[17:17:38 INFO]: Zombie Aggressive Towards Villager: true
[17:17:38 INFO]: Cactus Growth Modifier: 100%
[17:17:38 INFO]: Cane Growth Modifier: 100%
[17:17:38 INFO]: Melon Growth Modifier: 100%
[17:17:38 INFO]: Mushroom Growth Modifier: 100%
[17:17:38 INFO]: Pumpkin Growth Modifier: 100%
[17:17:38 INFO]: Sapling Growth Modifier: 100%
[17:17:38 INFO]: Beetroot Growth Modifier: 100%
[17:17:38 INFO]: Carrot Growth Modifier: 100%
[17:17:38 INFO]: Potato Growth Modifier: 100%
[17:17:38 INFO]: Wheat Growth Modifier: 100%
[17:17:38 INFO]: NetherWart Growth Modifier: 100%
[17:17:38 INFO]: Vine Growth Modifier: 100%
[17:17:38 INFO]: Cocoa Growth Modifier: 100%
[17:17:38 INFO]: Bamboo Growth Modifier: 100%
[17:17:38 INFO]: SweetBerry Growth Modifier: 100%
[17:17:38 INFO]: Kelp Growth Modifier: 100%
[17:17:38 INFO]: Experience Merge Radius: 3.0
[17:17:38 INFO]: Max TNT Explosions: 100
[17:17:38 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[17:17:38 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[17:17:38 INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[17:17:38 INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[17:17:38 INFO]: -------- World Settings For [world_the_end] --------
[17:17:38 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[17:17:38 INFO]: View Distance: 10
[17:17:38 INFO]: Item Merge Radius: 2.5
[17:17:38 INFO]: Item Despawn Rate: 6000
[17:17:38 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[17:17:38 INFO]: Mob Spawn Range: 6
[17:17:38 INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[17:17:38 INFO]: Nerfing mobs spawned from spawners: false
[17:17:38 INFO]: Zombie Aggressive Towards Villager: true
[17:17:38 INFO]: Cactus Growth Modifier: 100%
[17:17:38 INFO]: Cane Growth Modifier: 100%
[17:17:38 INFO]: Melon Growth Modifier: 100%
[17:17:38 INFO]: Mushroom Growth Modifier: 100%
[17:17:38 INFO]: Pumpkin Growth Modifier: 100%
[17:17:38 INFO]: Sapling Growth Modifier: 100%
[17:17:38 INFO]: Beetroot Growth Modifier: 100%
[17:17:38 INFO]: Carrot Growth Modifier: 100%
[17:17:38 INFO]: Potato Growth Modifier: 100%
[17:17:38 INFO]: Wheat Growth Modifier: 100%
[17:17:38 INFO]: NetherWart Growth Modifier: 100%
[17:17:38 INFO]: Vine Growth Modifier: 100%
[17:17:38 INFO]: Cocoa Growth Modifier: 100%
[17:17:38 INFO]: Bamboo Growth Modifier: 100%
[17:17:38 INFO]: SweetBerry Growth Modifier: 100%
[17:17:38 INFO]: Kelp Growth Modifier: 100%
[17:17:38 INFO]: Experience Merge Radius: 3.0
[17:17:38 INFO]: Max TNT Explosions: 100
[17:17:38 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[17:17:38 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[17:17:38 INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[17:17:38 INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[17:17:38 INFO]: Preparing start region for dimension minecraft:overworld
[17:17:38 INFO]: Loaded 0 spawn chunks for world world
[17:17:38 INFO]: Preparing spawn area: 0%
[17:17:38 INFO]: Time elapsed: 240 ms
[17:17:38 INFO]: Preparing start region for dimension minecraft:the_nether
[17:17:39 INFO]: Loaded 0 spawn chunks for world world_nether
[17:17:39 INFO]: Time elapsed: 196 ms
[17:17:39 INFO]: Preparing start region for dimension minecraft:the_end
[17:17:39 INFO]: Loaded 0 spawn chunks for world world_the_end
[17:17:39 INFO]: Preparing spawn area: 0%
[17:17:39 INFO]: Time elapsed: 395 ms
[17:17:39 INFO]: Running delayed init tasks
[17:17:39 INFO]: Done (4.858s)! For help, type "help"
[17:17:39 INFO]: Timings Reset
>

**Comment by EncryptSL** [comment]
For working my plugin you must have Java 14. Plugin are compiled on Java 14. You using java 8, or your hosting.

**Comment by Shucai99** [comment]
oh ok  like  dat? https://www.oracle.com/java/technologies/javase/jdk14-archive-downloads.html

**Comment by Shucai99** [comment]
[21:07:02 ERROR]: Could not pass event AsyncPlayerChatEvent to CensorReloaded v4.1.1
java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 71
[^(.* + \W|\d|_|.*|)?(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)+( .*)?$]
                                                                       ^
        at java.util.regex.Pattern.error(Pattern.java:2029) ~[?:?]
        at java.util.regex.Pattern.escape(Pattern.java:2620) ~[?:?]
        at java.util.regex.Pattern.range(Pattern.java:2806) ~[?:?]
        at java.util.regex.Pattern.clazz(Pattern.java:2716) ~[?:?]
        at java.util.regex.Pattern.sequence(Pattern.java:2140) ~[?:?]
        at java.util.regex.Pattern.expr(Pattern.java:2070) ~[?:?]
        at java.util.regex.Pattern.compile(Pattern.java:1784) ~[?:?]
        at java.util.regex.Pattern.<init>(Pattern.java:1431) ~[?:?]
        at java.util.regex.Pattern.compile(Pattern.java:1070) ~[?:?]
        at java.util.regex.Pattern.matches(Pattern.java:1175) ~[?:?]
        at java.lang.String.matches(String.java:2039) ~[?:?]
        at encryptsl.cekuj.net.module.AdwModul.adwModule(AdwModul.java:20) ~[?:?]
        at encryptsl.cekuj.net.filters.AsyncChat.asyncChat(AsyncChat.java:38) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor104.execute(Unknown Source) ~[?:?]        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-649]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Paper-649]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-649]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-649]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:225) ~[patched_1.16.5.jar:git-Paper-649]
        at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:105) ~[patched_1.16.5.jar:git-Paper-649]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:63) ~[patched_1.16.5.jar:git-Paper-649]
        at net.minecraft.server.v1_16_R3.PlayerConnection.chat(PlayerConnection.java:2088) ~[patched_1.16.5.jar:git-Paper-649]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2003) ~[patched_1.16.5.jar:git-Paper-649]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1941) ~[patched_1.16.5.jar:git-Paper-649]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:44) ~[patched_1.16.5.jar:git-Paper-649]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
[21:07:02 INFO]: <WillhelmDerProfi> 343.342
[21:07:07 INFO]: [MyCmd] Checking MySql Connection

**Comment by Shucai99** [comment]
[21:10:18 ERROR]: Could not pass event AsyncPlayerChatEvent to CensorReloaded v4.1.1
java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 71
[^(.* + \W|\d|_|.*|)?(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)+( .*)?$]
                                                                       ^
        at java.util.regex.Pattern.error(Pattern.java:2029) ~[?:?]
        at java.util.regex.Pattern.escape(Pattern.java:2620) ~[?:?]
        at java.util.regex.Pattern.range(Pattern.java:2806) ~[?:?]
        at java.util.regex.Pattern.clazz(Pattern.java:2716) ~[?:?]
        at java.util.regex.Pattern.sequence(Pattern.java:2140) ~[?:?]
        at java.util.regex.Pattern.expr(Pattern.java:2070) ~[?:?]
        at java.util.regex.Pattern.compile(Pattern.java:1784) ~[?:?]
        at java.util.regex.Pattern.<init>(Pattern.java:1431) ~[?:?]
        at java.util.regex.Pattern.compile(Pattern.java:1070) ~[?:?]
        at java.util.regex.Pattern.matches(Pattern.java:1175) ~[?:?]
        at java.lang.String.matches(String.java:2039) ~[?:?]
        at encryptsl.cekuj.net.module.AdwModul.adwModule(AdwModul.java:20) ~[?:?]
        at encryptsl.cekuj.net.filters.AsyncChat.asyncChat(AsyncChat.java:38) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-649]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Paper-649]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-649]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-649]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:225) ~[patched_1.16.5.jar:git-Paper-649]
        at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:105) ~[patched_1.16.5.jar:git-Paper-649]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:63) ~[patched_1.16.5.jar:git-Paper-649]
        at net.minecraft.server.v1_16_R3.PlayerConnection.chat(PlayerConnection.java:2088) ~[patched_1.16.5.jar:git-Paper-649]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2003) ~[patched_1.16.5.jar:git-Paper-649]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1941) ~[patched_1.16.5.jar:git-Paper-649]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:44) ~[patched_1.16.5.jar:git-Paper-649]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
[21:10:18 INFO]: <WillhelmDerProfi> hypixel.net

**Comment by Shucai99** [comment]
with  out ess chat

**Comment by EncryptSL** [comment]
Your config pls

**Comment by Shucai99** [comment]
from  what the  config censor or essn?

**Comment by EncryptSL** [comment]
Censor

**Comment by Shucai99** [comment]
CensorReloaded:
  node_website_whitelist:
  - www.example.com
  - https://www.example.com
  - http://www.exmaple.com
  node_check_cmd:
  - /msg
  - /pm
  - /tell
  - /r
  - /w
  node_module:
    pmCheck: true
    spam: true
    adw: true
    bad: true
    ip: true
  filters:
    capssens: 15
    adw_rgx:
    - ^(.* + \W|\d|_|.*|)?(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)+(
      .*)?$
    ip_rgx: ^(.* + \W|\d|_|.*)?\d{1,3}(\W|\d|\_|.*|)(\#|\.|\,\_\-\ \ \W|\d|\_|.*|)\d{1,3}(\W|\d|\_|.*|)(\#|\.|\,\_\-\
      \ \W|\d|\_|.*|)\d{1,3}(\W|\d|\_|.*|)(\#|\.|\,\_\-\ \ \W|\d|\_|.*|)\d{1,3}(\W|\d\_|.*)?$
  setup:
    prefix: '&5CENSOR-RELOADED &3> &c'
    lang: en_US
    bstats: true

**Comment by EncryptSL** [comment]
You can try remove your old configuration and stop server and start server,

**Comment by EncryptSL** [comment]
This is default config.yml of plugin. https://pastebin.com/7XJQSNNk

**Comment by EncryptSL** [comment]
Ok no problem
